#!/usr/bin/env python3
"""
SEO Audit Report Generator
Generates a structured SEO audit report in Markdown format.
Used by the marketing-ops skill for /marketing-ops seo audit.

Usage:
    python seo_audit.py --url "https://example.com" --output "seo-audit-example.md"
"""

import argparse
import json
from datetime import datetime
from pathlib import Path


def generate_audit_template(url: str, domain: str = None) -> str:
    """Generate a structured SEO audit report template."""
    if not domain:
        from urllib.parse import urlparse

        domain = urlparse(url).netloc or url

    date = datetime.now().strftime("%Y-%m-%d")

    report = f"""# SEO Audit Report — {domain}

**Date:** {date}
**URL Audited:** {url}
**Audited by:** Claude Marketing Ops

---

## Executive Summary

| Dimension | Score | Status |
|-----------|-------|--------|
| Technical SEO | /100 | 🟡 |
| On-Page SEO | /100 | 🟡 |
| Content Quality | /100 | 🟡 |
| Mobile Experience | /100 | 🟡 |
| Page Speed | /100 | 🟡 |
| **Overall** | **/100** | **🟡** |

### Top 3 Critical Issues
1. _[To be filled after analysis]_
2. _[To be filled after analysis]_
3. _[To be filled after analysis]_

### Estimated Impact
_[Traffic/revenue impact estimate of fixing critical issues]_

---

## Technical SEO

### Crawlability & Indexation
| Check | Status | Notes |
|-------|--------|-------|
| robots.txt accessible | ⬜ | |
| XML sitemap exists | ⬜ | |
| Sitemap submitted to GSC | ⬜ | |
| No blocked important pages | ⬜ | |
| Canonical tags correct | ⬜ | |
| No infinite crawl traps | ⬜ | |
| Hreflang (if multi-language) | ⬜ | |

### Site Performance
| Check | Status | Value | Target |
|-------|--------|-------|--------|
| Largest Contentful Paint (LCP) | ⬜ | _s | < 2.5s |
| Interaction to Next Paint (INP) | ⬜ | _ms | < 200ms |
| Cumulative Layout Shift (CLS) | ⬜ | _ | < 0.1 |
| Time to First Byte (TTFB) | ⬜ | _ms | < 800ms |
| Page size | ⬜ | _MB | < 3MB |
| Requests count | ⬜ | _ | < 50 |

### Security & Infrastructure
| Check | Status | Notes |
|-------|--------|-------|
| HTTPS everywhere | ⬜ | |
| No mixed content | ⬜ | |
| HTTP/2 or HTTP/3 | ⬜ | |
| Gzip/Brotli compression | ⬜ | |
| CDN configured | ⬜ | |
| Proper 404 handling | ⬜ | |
| No redirect chains (3+) | ⬜ | |

---

## On-Page SEO

### Page Elements
| Element | Current Value | Assessment | Recommendation |
|---------|--------------|------------|----------------|
| Title tag | | | |
| Meta description | | | |
| H1 tag | | | |
| H2 structure | | | |
| URL slug | | | |
| Image alt text | | | |
| Internal links | | | |
| External links | | | |
| Schema markup | | | |

### Content Analysis
| Check | Status | Notes |
|-------|--------|-------|
| Primary keyword in title | ⬜ | |
| Primary keyword in H1 | ⬜ | |
| Keyword in first 100 words | ⬜ | |
| Keyword density (1-2%) | ⬜ | |
| Semantic keywords present | ⬜ | |
| Content length vs competitors | ⬜ | |
| Unique value / angle | ⬜ | |
| Readability score | ⬜ | |

---

## Mobile Experience

| Check | Status | Notes |
|-------|--------|-------|
| Mobile-responsive design | ⬜ | |
| Touch targets ≥ 48px | ⬜ | |
| No horizontal scrolling | ⬜ | |
| Viewport meta tag | ⬜ | |
| Font size readable (≥16px) | ⬜ | |
| Mobile page speed | ⬜ | |

---

## Content Quality

| Check | Status | Notes |
|-------|--------|-------|
| No thin pages (<300 words) | ⬜ | |
| No duplicate content | ⬜ | |
| No keyword cannibalization | ⬜ | |
| Content freshness | ⬜ | |
| E-E-A-T signals | ⬜ | |
| Author bylines | ⬜ | |
| Last updated dates | ⬜ | |

---

## Quick Wins (Fix in < 1 Hour)

| # | Fix | Impact | Effort |
|---|-----|--------|--------|
| 1 | | High/Med/Low | Quick |
| 2 | | | Quick |
| 3 | | | Quick |
| 4 | | | Quick |
| 5 | | | Quick |

---

## Priority Action Plan

### Immediate (This Week)
1. _[Critical fix]_
2. _[Critical fix]_

### Short-term (This Month)
1. _[Important improvement]_
2. _[Important improvement]_

### Medium-term (This Quarter)
1. _[Growth opportunity]_
2. _[Growth opportunity]_

---

## Tools Used for This Audit
- Google PageSpeed Insights: https://pagespeed.web.dev/
- Google Search Console: https://search.google.com/search-console
- Google Rich Results Test: https://search.google.com/test/rich-results
- Mobile-Friendly Test: https://search.google.com/test/mobile-friendly
- Schema Validator: https://validator.schema.org/

---

*This audit was generated by Marketing Ops. Review each finding manually
and prioritize based on your specific business goals and resources.*
"""
    return report


def main():
    parser = argparse.ArgumentParser(description="Generate SEO Audit Report")
    parser.add_argument("--url", type=str, required=True, help="URL to audit")
    parser.add_argument("--output", type=str, default=None, help="Output file path")
    args = parser.parse_args()

    domain = None
    try:
        from urllib.parse import urlparse

        domain = urlparse(args.url).netloc
    except Exception:
        domain = args.url

    output_path = (
        args.output
        or f"seo-audit-{domain.replace('.', '-')}-{datetime.now().strftime('%Y-%m-%d')}.md"
    )

    report = generate_audit_template(args.url, domain)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"✅ SEO audit template generated: {output_path}")
    print(f"   URL: {args.url}")
    print(f"   Fill in findings after running the audit tools listed at the bottom.")


if __name__ == "__main__":
    main()
