#!/usr/bin/env python3
"""
FUSION MARKETS MANUAL PAPER TRADING SYSTEM
Simpler version - tanpa argparse yang error
"""

import json
from datetime import datetime
import time

class FusionManualTrader:
    """Manual Paper Trading Guide for Fusion Markets"""

    def __init__(self):
        self.credentials = {
            'username': 'Openclaw@12',
            'password': '10100262',
            'server': 'FusionMarkets-Demo'
        }
        self.symbol = 'XAUUSD'

    def show_credentials(self):
        """Display Fusion Markets credentials"""
        print("\n" + "="*80)
        print("🔐 FUSION MARKETS CREDENTIALS")
        print("="*80)
        print()
        print(f"   Username: {self.credentials['username']}")
        print(f"   Password: {'*' * len(self.credentials['password'])}")
        print(f"   Server: {self.credentials['server']}")
        print(f"   Account: Demo")
        print()
        print("="*80)
        print()
        print("⚠️  These are DEMO credentials - NO REAL MONEY")
        print("   Store securely and don't share with others")
        print()
        print("="*80)

    def web_setup_guide(self):
        """Provide web-based setup instructions"""
        print("\n" + "="*80)
        print("🌐 WEB-BASED SETUP (cTrader Webtrader)")
        print("="*80)
        print()
        print("Step 1: Open Fusion Markets cTrader Webtrader")
        print("   URL: https://fusionmarkets.com/Platforms/cTrader-Webtrader")
        print()
        print("Step 2: Login")
        print(f"   Username: {self.credentials['username']}")
        print(f"   Password: {'*' * len(self.credentials['password'])}")
        print(f"   Server: {self.credentials['server']} (should auto-select)")
        print()
        print("Step 3: Verify Account")
        print("   - Check demo account balance (should be $10,000)")
        print("   - Note: This is demo money - no real value")
        print()
        print("="*80)
        print()
        print("Step 4: Configure Chart")
        print(f"   Symbol: {self.symbol}")
        print("   Timeframe: H1 (1 Hour)")
        print("   - Click 'New Chart' button")
        print("   - Search for: XAUUSD or Gold")
        print("   - Select pair: XAUUSD")
        print("   - Set timeframe: H1")
        print()
        print("Step 5: Set Time Zone")
        print("   - Check chart time display (might be UTC)")
        print("   - Asia Session: 07:00-15:00 Jakarta (00:00-08:00 UTC)")
        print("   - Note: cTrader shows server time (not your local time)")
        print("   - Focus on candles during Asia session")
        print()
        print("="*80)
        print()

    def strategy_setup_guide(self):
        """Provide strategy setup instructions"""
        print("\n" + "="*80)
        print("📊 STRATEGY: XAUUSD ASIA 7-CANDLE BREAKOUT")
        print("="*80)
        print()
        print("Session Time: 07:00-15:00 Jakarta (00:00-08:00 UTC)")
        print()
        print("Entry Rules:")
        print("   1. Wait for 7 candles to form in Asia session")
        print("   2. Identify HH (Highest High) of 7 candles")
        print("   3. Identify LL (Lowest Low) of 7 candles")
        print("   4. Calculate Range: HH - LL")
        print()
        print("Filter Rule:")
        print("   - Only trade if Range ≥ 5 pips (0.50 for XAUUSD)")
        print("   - Skip day if range < 5 pips")
        print()
        print("Entry Orders:")
        print("   - Buy Stop: Set at HH (above current price)")
        print("   - Sell Stop: Set at LL (below current price)")
        print()
        print("Exit Rules:")
        print("   - Take Profit (TP): Entry + (Range × 2)")
        print("   - Stop Loss (SL): Entry - Range")
        print("   - Risk/Reward Ratio: 2:1")
        print()
        print("Risk Management:")
        print("   - Risk per trade: 1% of account balance")
        print("   - Max trades per day: 3")
        print("   - Stop trading after 3 consecutive losses")
        print("   - Lot Size: 0.01 (Mini lot for XAUUSD)")
        print("   - Pip Value: ~$0.10 per pip for 0.01 lot")
        print()
        print("Session End:")
        print("   - At 15:00 UTC (21:00 Jakarta), close any remaining positions")
        print("   - Don't hold positions overnight")
        print()
        print("="*80)
        print()

    def daily_checklist(self):
        """Daily trading checklist"""
        print("\n" + "="*80)
        print("✅ DAILY TRADING CHECKLIST")
        print("="*80)
        print()
        print("Before Asia Session (13:00 Jakarta):")
        print("   [ ] Login to Fusion Markets cTrader")
        print("   [ ] Check demo account balance")
        print("   [ ] Open XAUUSD H1 chart")
        print("   [ ] Review previous day's trades")
        print("   [ ] Note current market conditions")
        print()
        print("During Asia Session (13:00-21:00 Jakarta):")
        print("   [ ] Wait for 7 candles to form")
        print("   [ ] Identify HH and LL of 7 candles")
        print("   [ ] Calculate Range: HH - LL")
        print("   [ ] Check: Range ≥ 5 pips?")
        print("   [ ] If yes: Set Buy/Sell stops")
        print("   [ ] Set TP correctly (Entry + Range × 2)")
        print("   [ ] Set SL correctly (Entry - Range)")
        print("   [ ] Verify: Risk ≤ 1% of balance?")
        print("   [ ] Check: Trade count < 3 today?")
        print("   [ ] Monitor trades closely")
        print("   [ ] Record all trades in journal")
        print()
        print("After Session (21:00 Jakarta):")
        print("   [ ] Close all remaining positions")
        print("   [ ] Review day's trades")
        print("   [ ] Calculate day's PNL")
        print("   [ ] Update trading journal")
        print("   [ ] Note lessons learned")
        print("   [ ] Plan for tomorrow")
        print()
        print("="*80)
        print()

    def journal_template(self):
        """Provide journal template"""
        print("\n" + "="*80)
        print("📝 TRADING JOURNAL TEMPLATE")
        print("="*80)
        print()
        print("Copy this for each day's trading:")
        print()
        print("---" * 80)
        print(f"# [DATE] - Paper Trading Journal")
        print()
        print("## Summary")
        print("- Strategy: XAUUSD Asia 7-Candle Breakout")
        print("- Session Time: 07:00-15:00 Jakarta")
        print("- Account: Fusion Markets Demo")
        print("- Initial Balance: $[AMOUNT]")
        print("- Final Balance: $[AMOUNT]")
        print("- Net PNL: $[AMOUNT]")
        print()
        print("## Market Conditions")
        print("- Volatility: [Low/Medium/High]")
        print("- Session Range: [MIN] - [MAX] pips")
        print("- Trends: [Up/Down/Sideways]")
        print("- Notes: [Any observations]")
        print()
        print("## Trades")
        print()
        print("### Trade 1")
        print("- Time: [TIME]")
        print("- Type: [Buy/Sell]")
        print("- Entry: $[PRICE]")
        print("- TP: $[PRICE]")
        print("- SL: $[PRICE]")
        print("- Exit: [TP Hit/SL Hit/Session End]")
        print("- PNL: $[AMOUNT]")
        print("- Result: [Win/Loss]")
        print("- Notes: [Any observations]")
        print()
        print("### Trade 2")
        print("- Time: [TIME]")
        print("- Type: [Buy/Sell]")
        print("- Entry: $[PRICE]")
        print("- TP: $[PRICE]")
        print("- SL: $[PRICE]")
        print("- Exit: [TP Hit/SL Hit/Session End]")
        print("- PNL: $[AMOUNT]")
        print("- Result: [Win/Loss]")
        print("- Notes: [Any observations]")
        print()
        print("### Trade 3")
        print("- Time: [TIME]")
        print("- Type: [Buy/Sell]")
        print("- Entry: $[PRICE]")
        print("- TP: $[PRICE]")
        print("- SL: $[PRICE]")
        print("- Exit: [TP Hit/SL Hit/Session End]")
        print("- PNL: $[AMOUNT]")
        print("- Result: [Win/Loss]")
        print("- Notes: [Any observations]")
        print()
        print("## Lessons Learned")
        print("- What worked:")
        print("- What didn't:")
        print("- Improvements needed:")
        print("- Mental state:")
        print()
        print("## Tomorrow's Plan")
        print("- Adjustments to strategy:")
        print("- Risk management changes:")
        print("- Goals:")
        print()
        print("---" * 80)
        print()
        print("="*80)
        print()

    def performance_tracking(self):
        """Provide performance tracking template"""
        print("\n" + "="*80)
        print("📊 WEEKLY METRICS")
        print("="*80)
        print()
        print("Track at end of each week:")
        print()
        print("| Week | PNL | Win Rate | Total Trades | Max DD |")
        print("|------|-----|----------|--------------|--------|")
        print("| Week 1| | | | | |")
        print("| Week 2| | | | | |")
        print("| Week 3| | | | | |")
        print("| Week 4| | | | | |")
        print()
        print("="*80)
        print()
        print("MONTHLY GOALS")
        print()
        print("| Month | Goal PNL | Actual PNL | Target WR | Actual WR |")
        print("|-------|----------|------------|-----------|----------|")
        print("| Month 1| +$100| | | 60%| | |")
        print("| Month 2| +$200| | | 60%| | |")
        print("| Month 3| | | | | |")
        print()
        print("="*80)
        print()

    def main_menu(self):
        """Display main menu"""
        print("\n" + "="*80)
        print("FUSION MARKETS MANUAL PAPER TRADING SYSTEM")
        print("="*80)
        print()
        print("XAUUSD ASIA 7-CANDLE BREAKOUT STRATEGY")
        print("Proven: 61.4% Win Rate, +$528 PNL in backtest")
        print("="*80)
        print()
        print("📋 MAIN MENU")
        print()
        print("1. ✅ Show Credentials")
        print("2. 🌐 Web-Based Setup Instructions")
        print("3. 📊 Strategy Setup Guide")
        print("4. ✅ Daily Trading Checklist")
        print("5. 📝 Journal Template")
        print("6. 📈 Performance Tracking Template")
        print("7. 🎯 Success Criteria & Goals")
        print("8. ⚠️  Important Reminders")
        print("9. 🚪 Exit")
        print()
        print("="*80)
        print()
        print("Choose option (1-9): ", end='')

        choice = input().strip()

        if choice == '1':
            self.show_credentials()
        elif choice == '2':
            self.web_setup_guide()
        elif choice == '3':
            self.strategy_setup_guide()
        elif choice == '4':
            self.daily_checklist()
        elif choice == '5':
            self.journal_template()
        elif choice == '6':
            self.performance_tracking()
        elif choice == '7':
            print("\n" + "="*80)
            print("🎯 SUCCESS CRITERIA")
            print("="*80)
            print()
            print("Minimum 4 weeks of profitable paper trading")
            print()
            print("Metrics:")
            print("  ✅ Weekly PNL positive for 4 consecutive weeks")
            print("  ✅ Win Rate ≥ 60%")
            print("  ✅ Max Drawdown ≤ 15%")
            print("  ✅ Consistent execution of strategy rules")
            print("  ✅ No revenge trading")
            print("  ✅ Disciplined risk management (1% per trade)")
            print()
            print("Live Trading Prerequisites:")
            print("  ✅ Demo balance grew from $10,000 to $15,000+ (50%+ growth)")
            print("  ✅ Demonstrated ability to compound profits")
            print("  ✅ Psychology ready: Comfortable with losses")
            print("  ✅ Learned from paper trading mistakes")
            print()
            print("="*80)
            print()
            print("Recommended First Live Trading Setup:")
            print("  ✅ Open live account with Fusion Markets")
            print("  ✅ Deposit: $500-$1,000 (start small)")
            print("  ✅ Use same strategy (XAUUSD Asia 7-Candle)")
            print("  ✅ Start with 0.01 lot size")
            print("  ✅ Monitor closely for first 2-4 weeks")
            print("  ✅ Scale up gradually as confidence grows")
            print()
            print("="*80)
        elif choice == '8':
            print("\n" + "="*80)
            print("⚠️  IMPORTANT REMINDERS")
            print("="*80)
            print()
            print("🚫 DEMO ACCOUNT")
            print("  - You are trading with DEMO money")
            print("  - NO REAL MONEY at risk")
            print("  - This is for PRACTICE and LEARNING")
            print()
            print("📋 RECORD EVERYTHING")
            print("  - All trades must be recorded in journal")
            print("  - Include: Date, Type, Entry, TP, SL, Exit, PNL, Result")
            print("  - Notes: What you learned, mistakes, observations")
            print()
            print("🎯 FOCUS ON LEARNING")
            print("  - Don't focus on profit/loss amounts")
            print("  - Focus on executing strategy correctly")
            print("  - Focus on discipline and consistency")
            print("  - Learn from every mistake")
            print()
            print("⚠️  NO REAL TRADING YET")
            print("  - DO NOT deposit real money")
            print("  - Wait until 4+ profitable weeks")
            print("  - Wait until you meet success criteria")
            print("  - Paper trading is the PREPARATION phase")
            print()
            print("🔐 SECURE YOUR CREDENTIALS")
            print("  - Don't share these demo credentials")
            print("  - Use different password for live account")
            print("  - Store securely")
            print()
            print("⏰ ASIA SESSION ONLY")
            print("  - XAUUSD Asia 7-Candle is optimized for Asia session")
            print("  - Best results: 07:00-15:00 Jakarta Time")
            print("  - Don't trade during London/NY sessions")
            print()
            print("="*80)
            print()
        elif choice == '9':
            print("\n" + "="*80)
            print("👋 GOOD LUCK WITH YOUR PAPER TRADING!")
            print("="*80)
            print()
            print("Remember:")
            print("  ✅ Practice makes perfect")
            print("  ✅ Learn from every trade")
            print("  ✅ Stay disciplined")
            print("  ✅ Don't revenge trade")
            print("  ✅ Follow the strategy rules")
            print()
            print("Paper trading is your path to profitable live trading!")
            print()
            print("="*80)
            print()
            print("To start again, run this script: python fusion_manual_trading.py")
            print()
        else:
            print("\n❌ Invalid choice. Try again.")

def main():
    trader = FusionManualTrader()
    trader.main_menu()

if __name__ == "__main__":
    main()
