#!/usr/bin/env python3
"""
PLAYWRIGHT BROWSER LAUNCH
Simpler version - Just open browser for Fusion Markets cTrader
"""

import asyncio
from playwright.sync_api import sync_playwright

def launch_browser():
    """Launch browser for Fusion Markets cTrader"""
    print("🎭 Launching Playwright Browser...")
    print()

    with sync_playwright() as p:
        print("✅ Playwright loaded")
        print()
        print("🔗 Connecting to Fusion Markets cTrader...")
        print()

        # Launch browser (chromium with window)
        browser = p.chromium.launch(
            headless=False,
            slow_mo=100,
            args=['--no-sandbox', '--disable-setuid-sandbox']
        )

        print("✅ Browser launched (Chromium)")
        print()
        print("🌐 Opening Fusion Markets cTrader Webtrader...")
        print()

        # Navigate to Fusion Markets cTrader Webtrader
        page = browser.new_page()
        page.goto("https://fusionmarkets.com/Platforms/cTrader-Webtrader")

        print("✅ Page loaded: https://fusionmarkets.com/Platforms/cTrader-Webtrader")
        print()
        print("="*80)
        print("📋 FUSION MARKETS CREDENTIALS")
        print("="*80)
        print(f"   Username: Openclaw@12")
        print(f"   Password: 10100262")
        print(f"   Server: FusionMarkets-Demo")
        print(f"   Account: Demo")
        print()
        print("="*80)
        print("📋 MANUAL LOGIN STEPS")
        print("="*80)
        print()
        print("STEP 1: Enter Credentials")
        print("   - Copy username: Openclaw@12")
        print("   - Copy password: 10100262")
        print("   - Paste into login form")
        print()
        print("STEP 2: Select Server")
        print("   - Select: FusionMarkets-Demo")
        print("   - Click 'Login'")
        print()
        print("STEP 3: Verify Account")
        print("   - Check 'Accounts' section")
        print("   - Note demo balance (should be ~$10,000)")
        print("   - Remember: This is DEMO money - NO REAL VALUE")
        print()
        print("STEP 4: Setup XAUUSD Chart")
        print("   - Click 'New Chart'")
        print("   - Search: XAUUSD or Gold")
        print("   - Select: XAUUSD")
        print("   - Set Timeframe: H1 (1 Hour)")
        print()
        print("="*80)
        print("📊 XAUUSD ASIA 7-CANDLE BREAKOUT STRATEGY")
        print("="*80)
        print()
        print("Session: Asia (07:00-15:00 Jakarta Time)")
        print("Entry: Buy/Sell stop at HH/LL of 7 candles")
        print("Filter: Range ≥ 5 pips (0.50 for XAUUSD)")
        print("Exit: TP = Entry + (Range × 2), SL = Entry - Range")
        print("Risk: 1% per trade")
        print("Max Trades: 3 per day")
        print()
        print("="*80)
        print("📋 DAILY TRADING CHECKLIST")
        print("="*80)
        print()
        print("Before Session (13:00 Jakarta):")
        print("   [ ] Login verified")
        print("   [ ] Chart XAUUSD H1 opened")
        print("   [ ] Previous day's trades reviewed")
        print()
        print("During Session (13:00-21:00 Jakarta):")
        print("   [ ] Wait for 7 candles to form")
        print("   [ ] Identify HH and LL")
        print("   [ ] Calculate Range: HH - LL")
        print("   [ ] Check: Range ≥ 5 pips?")
        print("   [ ] If yes: Set Buy/Sell stops")
        print("   [ ] Set TP and SL correctly")
        print("   [ ] Verify: Risk ≤ 1% of balance?")
        print("   [ ] Verify: Trade count < 3 today?")
        print("   [ ] Monitor trades closely")
        print()
        print("After Session (21:00 Jakarta):")
        print("   [ ] Close all remaining positions")
        print("   [ ] Review day's trades")
        print("   [ ] Calculate day's PNL")
        print("   [ ] Update trading journal")
        print()
        print("="*80)
        print("🖥️  BROWSER READY FOR MANUAL TRADING")
        print("="*80)
        print()
        print("✅ Browser is open and ready!")
        print("✅ Fusion Markets cTrader Webtrader is loaded")
        print("✅ Credentials and instructions are provided above")
        print()
        print("⚠️  IMPORTANT REMINDERS:")
        print("   - DEMO ACCOUNT - NO REAL MONEY")
        print("   - Practice and learn the strategy")
        print("   - Follow rules 100% - no emotions")
        print("   - Focus on execution, not profit")
        print("   - Journal everything")
        print()
        print("🎯 TARGET: 4-8 weeks of profitable paper trading")
        print("   - Win Rate: ≥ 60%")
        print("   - Net PNL: Positive")
        print("   - Max Drawdown: ≤ 15%")
        print()
        print("📝 Journal Template (copy for each day):")
        print()
        print("```")
        print("# [DATE] - Paper Trading Journal")
        print()
        print("## Summary")
        print("- Strategy: XAUUSD Asia 7-Candle Breakout")
        print("- Session: 07:00-15:00 Jakarta")
        print("- Initial Balance: $[AMOUNT]")
        print("- Final Balance: $[AMOUNT]")
        print("- Net PNL: $[AMOUNT]")
        print()
        print("## Market Conditions")
        print("- Volatility: [Low/Medium/High]")
        print("- Session Range: [MIN] - [MAX] pips")
        print("- Notes: [Any observations]")
        print()
        print("## Trades")
        print()
        print("### Trade 1")
        print("- Time: [TIME]")
        print("- Type: [Buy/Sell]")
        print("- Entry: $[PRICE]")
        print("- TP: $[PRICE]")
        print("- SL: $[PRICE]")
        print("- Exit: [TP Hit/SL Hit/Session End]")
        print("- PNL: $[AMOUNT]")
        print("- Result: [Win/Loss]")
        print("- Notes: [Any observations]")
        print()
        print("## Lessons Learned")
        print("- What worked:")
        print("- What didn't:")
        print("- Improvements needed:")
        print("- Mental state:")
        print()
        print("## Tomorrow's Plan")
        print("- Adjustments to strategy:")
        print("- Risk management changes:")
        print("- Goals:")
        print("```")
        print()
        print("="*80)
        print("✅ SETUP COMPLETE!")
        print("="*80)
        print()
        print("🖥️  Browser will remain open...")
        print("   Navigate through the interface manually")
        print("   Execute trades according to the strategy")
        print("   The browser window will close after you close it")
        print()
        print("🚀 GOOD LUCK WITH YOUR PAPER TRADING!")
        print("="*80)

        # Keep browser open (don't close immediately)
        input("Press Enter to close browser when done...")

        # Close browser
        browser.close()
        print()
        print("✅ Browser closed")
        print()
        print("="*80)
        print("COMPLETE")
        print("="*80)

if __name__ == "__main__":
    launch_browser()
