#!/bin/bash

echo "═══════════════════════════════════════════════════════════"
echo "  1ai-Skills Discord Server Setup Guide"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "STEPS TO CREATE DISCORD SERVER:"
echo ""
echo "1. Create Server:"
echo "   - Open Discord"
echo "   - Click '+' → Create My Own"
echo "   - Name: 1ai-Skills Hub"
echo ""
echo "2. Categories (create in this order):"
echo "   📢 INFORMATION"
echo "   💬 DISCUSSION"
echo "   🎯 SKILL CATEGORIES"
echo "   🔧 SUPPORT"
echo "   🎓 ADVANCED"
echo ""
echo "3. Channels by category:"
echo ""
echo "📢 INFORMATION"
echo "   #welcome #announcements #getting-started #faq"
echo ""
echo "💬 DISCUSSION"
echo "   #general #skill-ideas #showcase #wins #feedback"
echo ""
echo "🎯 SKILL CATEGORIES"
echo "   #trading #marketing #finance #productivity #development #automation"
echo ""
echo "🔧 SUPPORT"
echo "   #skill-support #bug-reports #feature-requests"
echo ""
echo "🎓 ADVANCED"
echo "   #contributors #beta-testing #partnerships"
echo ""
echo "4. Set welcome message in #welcome"
echo "5. Create permanent invite link"
echo "6. Share on social media"
echo ""
echo "═══════════════════════════════════════════════════════════"
