#!/usr/bin/bash
# Setup TikTok Authenticaton untuk JENDRALBOT Campaign
# Credentials dari: @Andik veris (Andik veris / alwayscuanbos / nugrohopratama5)
# Password: 1Milyarberkah

echo "🎯 SETUP TIKTOK AUTHENTICATION - JENDRALBOT" 
echo "==================================="
echo ""
echo "✅ Credentials dari boss diterima!"
echo ""
echo "🔑 USERNAME: nugrohopratama5"
echo "🔑 PASSWORD: 1Milyarberkah"
echo ""
echo "📁 CONFIG: /home/openclaw/.openclaw/workspace/skills/tiktokautomation/config.json"
echo "🔑 ASSETS: /home/openclaw/.openclaw/workspace/skills/tiktokautomation/assets/"
echo ""
echo "🎯 18 Hook Frames SIAP di assets/"
ls -lah /home/openclaw/.openclaw/workspace/skills/tiktokautomation/assets/*.png | wc -l
echo ""
echo "🔑 AUTH FLOW:"
echo "1. Jalankan script auth: /home/openclaw/.openclaw/workspace/skills/tiktok-automation/scripts/auth_setup.sh"
echo "   - Akan membuka browser di komputer boss"
echo "   - Login ke TikTok"
echo "   - Authorize aplikasi JENDRALBOT di Canva popup"
echo "   - Selesai! Token akan tersimpan otomatis"
echo ""
echo "🔑 DEO UPLOAD:"
echo "cd /home/openclaw/.openclaw/workspace/skills/tiktokautomation/"
echo "python3 jendralbot_single_upload.py <nama_file.png> --caption <caption> --tags <tags>"
echo ""
echo "🔑 BATCH UPLOAD SEMUA 18 HOOKS:"
echo "cd /home/openclaw/.openclaw/workspace/skills/tiktokautomation/"
echo "python3 batch_upload_all_hooks.py"
echo ""
echo "==================================="
echo ""
echo "✅ CONFIG SUDAH DIUPDATE DENGAN KREDENSIALS BOSS."
echo "🔑 READY UNTUK AUTH -> AUTO-LEAD! 🚀"
echo "Tinggal upload video, caption, hashtags jadi otomatis!"