#!/bin/bash
# Setup TikTok Authentication - JENDRALBOT Campaign
# Instructions untuk boss

echo "🎯 SETUP AUTENTIKASI TIKTOK OLEH BOS"
echo "=================================="
echo ""
echo "HAL YANG PERLU BOSS LAKUAN:"
echo ""
echo "1. Login ke TikTok di browser boss"
echo "   Buka browser → https://www.tiktok.com"
echo "   Login dengan akun TikTok boss"
echo ""
echo "2. Buka file ini: /home/openclaw/.openclaw/workspace/skills/tiktok-automation/scripts/setup_auth.sh"
echo "   Saya akan buka browser di komputer boss untuk authorize"
echo ""
echo "3. Di Canva popup/authorization:"
echo "   Klik tombol 'Connect' atau 'Allow'"
echo "   Izinkan aplikasi JENDRALBOT"
echo ""
echo "4. Jika sukses → Selesai! Token akan tersimpan otomatis"
echo ""
echo "5. Test upload dengan script:"
echo "   cd /home/openclaw/.openclaw/workspace/skills/tiktok-automation"
echo "   ./script.sh --video assets/belanja_duit_balik_hook1_shock.png --caption 'GILA! BELANJA DU TETAP BALIK!' --tags '#cashback'"
echo ""
echo "=================================="
echo ""
echo "📝 CONFIG YANG PERLU DI-EDIT:"
echo ""
echo "File: /home/openclaw/.openclaw/workspace/skills/tiktok-automation/config.json"
echo ""
echo "Ganti bagian username + password dengan:"
echo "  \"credentials\": {"
echo "    \"username\": \"ISI_BOS_USERNAME_TIKTOK\","
echo "    \"password\": \"ISI_BOS_PASSWORD_TIKTOK\""
echo "  }"
echo ""
echo "📞 KEMUDIAN VIDEO KE ASSETS:"
echo "All hook frames sudah di: /home/openclaw/.openclaw/workspace/skills/tiktok-automation/assets/"
echo ""
echo "=================================="
echo ""
echo "MULAIKAN KE BROWSER SEKARANG BOSS!"